[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gcutils"
description = "A simple package with utility Python functions used for analysis of complete Mtb genomes"
readme = "README.md"
version = "0.0.1"
authors = [
    { name = "Maximillian Marin", email = "maximilliangmarin@gmail.com" }
]

requires-python = ">=3.7"
dependencies = ["pandas",
                "bioframe"]


[project.scripts]
gcutils = "gcutils.__init__:main"


[project.urls]
"Homepage" = "https://github.com/maxgmarin/mtb-geneconv-manuscript"
